# Generated by Django 3.2.13 on 2022-05-25 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last_name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last_name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('school', models.IntegerField(verbose_name='Number_of_the_school')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Title')),
                ('text', models.CharField(default='', max_length=500, verbose_name='Text')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('id_checking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
                ('id_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
