# Generated by Django 3.2.13 on 2022-05-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='email_student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='first_name_student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='last_name_student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='password_student',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='email',
            new_name='email_teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='first_name_teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='last_name',
            new_name='last_name_teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='password',
            new_name='password_teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='school',
            new_name='school_teacher',
        ),
    ]
